version: '3'
services:
   nginx:
      image: nginx:stable
      container_name: nginx
      network_mode: host
      volumes:
         - ./nginx:/etc/nginx/conf.d/
   db:
      image: postgres:11.4
      container_name: clinwiki-db
      ports:
         - 15432:5432
      environment:
         - POSTGRES_USER=clinwiki
         - POSTGRES_PASSWORD=ZetIFOnXd78H
      volumes:
         - cw-data:/var/lib/postgresq/data
   elastic:
      image: elasticsearch:6.8.1
      container_name: elastic
      network_mode: host
      environment:
         - discovery.type=single-node
      ulimits:
         memlock:
            soft: -1
            hard: -1
      volumes:
         - es-data:/usr/share/elasticsearch/data/
   redis:
      image: redis:5.0.5
      container_name: redis
      network_mode: host
      volumes:
         - redis-data:/data
   clinwiki:
      #build: ./
      image: cwlite
      container_name: clinwiki
      network_mode: host
      volumes:
         - ../:/clinwiki
         - ./entrypoint.sh:/usr/bin/entrypoint.sh
      environment:
         - DATABASE_URL=postgres://clinwiki:ZetIFOnXd78H@localhost:15432/clinwiki
         - AACT_DATABASE_URL=postgres://clinwiki:JQIhi3AGyBwl@aact.clinwiki.org:5432/aact
         - REDIS_URL=redis://127.0.0.1:6379/0
        # - RAILS_ENV=production
        # - RACK_ENV=production
        # - RAILS_SERVE_STATIC_FILES=enabled
      depends_on: 
         - db
         - elastic
         - redis
# Having trouble when attempting to turn sidekiq in a separate container
#   sidekiq:
#      image: cwlite
#      container_name: sidekiq
#      network_mode: host
#      command: bundle exec sidekiq -C config/sidekiq.yml
#      volumes:
#         - ./clinwiki:/clinwiki
#      environment:
#         - DATABASE_URL=postgres://clinwiki:ZetIFOnXd78H@localhost:5432/clinwiki
#         - AACT_DATABASE_URL=postgres://clinwiki:JQIhi3AGyBwl@aact.clinwiki.org:5432/aact
#         - REDIS_URL=redis://127.0.0.1:6379/0
#      depends_on: 
#         - db
#         - elastic
#         - redis
#         - clinwiki
volumes:
   es-data:
   cw-data:
   aact-data:
   redis-data:

